### PR TITLE
format columns on app review page

### PR DESCRIPTION
**Pull request by elissaperdue**

### CODE REVIEW

**Comment by abigger87** [comment]
@elissaperdue can you send a screenshot? I made flex-wrap set to wrap so when its on mobile the columns flex and they look nice

**Comment by MaxLeiter** [comment]
@elissaperdue it looks great in desktop view but as @abigger87 pointed out the mobile view needs to switch to full columns (like how it was before) although I don't think we should put too much effort into mobile on this; reviewers should be using a computer and giving it their full attention

**Comment by elissaperdue** [comment]
@abigger87 @MaxLeiter makes sense so how should we proceed? I have some ideas to make it mobile friendly as well with a different approach, but is it worth more time?

**Comment by abigger87** [comment]
If you have time to take a stab go for it, unless you can tackle some of the other issues. @MaxLeiter  and I need to plan a bit more for the hackathon since team matching and judging are nearing completion ... we need to plan out battlepass, how we check in hackers, houses, event schedule...

**Comment by MaxLeiter** [comment]
One small problem - we should probably just hide 'review' if its mobile 
Screen Shot 2020-12-29 at 1 28 39 PM

**Comment by abigger87** [comment]
> One small problem - we should probably just hide 'review' if its mobile
> Screen Shot 2020-12-29 at 1 28 39 PM

wdym? why would we hide review?
accessibility should def allow ppl to review on phones...

**Review by abigger87 — APPROVED** [review]

**Comment by abigger87** [comment]
lets merge, try it out on staging, and we can always revert

**Comment by MaxLeiter** [comment]
@abigger87 I meant the word review in that screenshot

**Comment by abigger87** [comment]
oh gotcha, we can fit that in a new styling pr...

**Comment by abigger87** [comment]
ill merge for now and we can check in staging

**Pull request merged**
