### PR TITLE
Profile

### PR DESCRIPTION
**Pull request by chloetanlimco**
Stuff on this PR (relatively simple):
- Set up frontend (c/o Wilson's design)
- Edit profile fields that we currently have available (firstName, lastName, school, major, year) 

Questions: 
- Should we pull in team matching from staging/main into this branch? 
- How do we feel about the pop-up design? I have not implemented that but should be relatively straightforward fix
- How should we do profile image upload? Are we storing on aws?

### CODE REVIEW

**Comment by abigger87** [comment]
> Questions:
> 
> * Should we pull in team matching from staging/main into this branch?
> * How do we feel about the pop-up design? I have not implemented that but should be relatively straightforward fix
> * How should we do profile image upload? Are we storing on aws?

- Probably a good idea. We should work a staging/main merge back into the dashboard branch.
- I'm not sure about the pop-up, @MaxLeiter ?
- Yes AWS should work there are a few examples in the api (I think admin/resume or admin/uploadResume or something like that) I will quickly create a subfolder in hacksc-odyssey bucket called profile-pictures so it can be referenced by `hacksc-odyssey/profile-pictures/` on upload.

**Comment by chloetanlimco** [comment]
image
image
image
image

Tried to emulate current dashboard styles

**Comment by abigger87** [comment]
looks really good 👍 just fixed build and am trying to fix the coverage tests

**Comment by abigger87** [comment]
I'm sending a merge here so dashboard is up to date

**Comment by chloetanlimco** [comment]
@abigger87 thanks for fixing build!

**Pull request merged**
